export type RootStackParamList = {
  Home: undefined;
  Details: undefined;
  SimpleTheme: undefined;
  BorderShapes: undefined;
  Position: undefined;
  MyProfile: undefined;
  Transforms: undefined;
  Flexbox: undefined;
  List: undefined;
  Input: undefined;
  ScrollableList: undefined;
  Modal: undefined;
  Touches: undefined;
  // KeyboardAvoiding: undefined;
  LayoutAnimation: undefined;
  BoxAnimate: undefined;
  TextInputAnimate: undefined;
  SimplePanResponder: undefined;
  PanResponder: undefined;
  SpinningAnimation: undefined;
  AnimatedWelcome: undefined;
  AnimationSequence: undefined;
  AnimationStaggering: undefined;
  SwipableDeck: undefined;
};
